FROM node:20

WORKDIR /apps

COPY core/package*.json core/
COPY core/tsconfig.json core/

COPY user-service/package*.json user-service/
COPY user-service/tsconfig.json user-service/
COPY user-service/prisma.config.ts user-service/
COPY user-service/prisma user-service/prisma

WORKDIR /apps/core
RUN npm install

WORKDIR /apps/user-service
RUN npm install

WORKDIR /apps
COPY core/src core/src
COPY user-service/src user-service/src

WORKDIR /apps/core
RUN npm run build

WORKDIR /apps/user-service

EXPOSE 3001

CMD npm run dev
